export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const DANG_KI_ACTION = "DANG_KI_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const SUA_THONG_TIN_NGUOI_DUNG = "SUA_THONG_TIN_NGUOI_DUNG";
export const SUA_THONG_TIN_NGUOI_DUNG_EDIT = "SUA_THONG_TIN_NGUOI_DUNG_EDIT";
export const LAY_DANH_SACH_NGUOI_DUNG = "LAY_DANH_SACH_NGUOI_DUNG";
export const TIM_NGUOI_DUNG_THEO_TU_KHOA = "TIM_NGUOI_DUNG_THEO_TU_KHOA";
export const LAY_DANH_SACH_NGUOI_DUNG_THEO_TU_KHOA =
  "LAY_DANH_SACH_NGUOI_DUNG_THEO_TU_KHOA";
